### ISSUE TITLE
if a nested route is within a fixed height container, the reset scroll doesn't work.

### ISSUE THREAD

**Issue by NullVoxPopuli** [dollarshaveclub/ember-router-scroll#56]
The scenario is if you have a sticky header and sticky footer.

My main div that all my routes are rendered in has these styles:

```scss
// sticky-footer styles
.inner-wrap {
  height: 100%;
  height: 100vh; // this and the overflow causes the app scroll to be in a nested scrollbar.
  overflow-x: hidden;
  background: white;
  min-height: 100%;
  display: flex;
  flex-direction: column;

  section.main-section, .shell, .inner-shell {
    flex: 1;
    // my app pretty much lives here
  }

  .sticky-footer {
    margin-top: 40px;
  }
}
```

So, I guess is there a way to specify what dom element has its scroll reset? maybe an array of selectors to specify?
